name: Node.js CI/CD

on:
  push:
    branches:
      - production # Specify the branch you want to trigger the action on

jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - run: npm ci
      - run: npm test

      # Add your deployment step here, e.g., pm2 restart, but only for the 'production' branch
      - name: Deploy to production
        if: github.ref == 'refs/heads/production' # This step will run only for the 'production' branch
        run: pm2 restart backendserver
